services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"

  web:
    image: nowyousleep/test-blog-web
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:12345@db:5432/postgres
