
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 34615
  host: localhost
  port: 5432

development:
  <<: *default
  database: test_blog_development

test:
  <<: *default
  database: test_blog_test


production:
  <<: *default
  database: test_blog_production
  username: test_blog
  password: <%= ENV["TEST_BLOG_DATABASE_PASSWORD"] %>
